# Generated by Django 2.0.2 on 2018-02-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAlumno', models.CharField(max_length=40)),
                ('ApellidoParterno', models.CharField(max_length=40)),
                ('ApellidoMarterno', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=250)),
                ('Edad', models.IntegerField()),
                ('Semestre', models.IntegerField()),
                ('Carrera', models.CharField(max_length=100)),
                ('Especialidad', models.CharField(max_length=100)),
            ],
        ),
    ]
